# -*- coding: utf-8 -*-
"""SLRModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18JhRfaNTqHI-amUKM-v-rD1-80YkRwgj
"""

class SLR:
  def __init__(self, dataset):
    self.dataset = dataset
    self.b_0 = 0
    self.b_1 = 0
    self.yhat = 0
    self.x = 0

  def calculate(self):
    sum_x = sum(x[0] for x in self.dataset)
    sum_y = sum(x[1] for x in self.dataset)
    sum_xsquare = sum(x[0]**2 for x in self.dataset)
    sum_xy = sum(x[0] * x[1] for x in self.dataset)
    n = len(self.dataset)

    self.b_0 = (sum_xsquare * sum_y - (sum_x * sum_xy)) / (n * sum_xsquare - sum_x**2)
    self.b_1 = (n * sum_xy - (sum_x * sum_y)) / (n * sum_xsquare - sum_x**2)

  def predict(self, x):
    self.x = x
    self.calculate()
    self.yhat = self.b_0 + self.b_1 * self.x

  def print_results(self):
    print(f"ŷ = {self.b_0:.2f} + {self.b_1:.2f} * {self.x:.2f}")
    print(f"ŷ = {self.yhat:.2f}")


def main():
  dataset = [
        (23, 651),
        (26, 762),
        (30, 856),
        (34, 1063),
        (43, 1190),
        (48, 1298),
        (52, 1421),
        (57, 1440),
        (58, 1518),
        ]

  slr = SLR(dataset)
  slr.predict(58)
  slr.print_results()

if __name__ == "__main__":
  main()